version: "1"


services:

  nginx-proxy :
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  
  web:
    container_name: web_cv_nginx
    image: nginx:latest
    expose:
      - "80"
    volumes:
      - /home/pi/programas/web:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST="10.56.77.111" 


